// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sirawitchchairuangsirikul

// plot มาก่อนแล้วมาสังเกตแล้วดูว่าใช้ขนาดเท่าไหร่ดี 0.005,0.0025

//@version=6
indicator("EURUSD line",overlay=true)

// input
len = input.float(25, "length", minval=0)
numLevel = input.int(20,"number line",minval=0)
startLevel = input.float(525,"strat level",minval=0)

// plot line level
for i = 0 to numLevel
    float level = startLevel + (len * i)

    line.new(x1=bar_index, y1=level, x2=bar_index + 100, y2=level, color=color.gray, width=1, extend=extend.right, xloc=xloc.bar_time)